# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIr1r9XdU6g4PZQkjuBk0ykYOR_3rIyF
"""

# Only run if starting fresh
!pip install -q torch torchvision tensorboard
print('Done.')

# ── Imports & Config ──────────────────────────────────────────────────────────
# FIX: all imports consolidated here at the top so every function below can
# reference np, cv2, torch, etc. without NameError regardless of cell order.
# The original file had the import block at line ~358 (after augmentation and
# dataset code that already used these names) and also re-imported cv2/np at
# line 601 mid-training-loop — both redundant instances removed.

import os
import json
import time
import random
from pathlib import Path

import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import matplotlib.pyplot as plt
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter

# Mount Drive and set paths
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

BASE = '/content/drive/MyDrive/augle_ai'

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {DEVICE}')

CFG = {
    'coco_path':      f'{BASE}/data/annotations/instances.json',
    'image_root':     f'{BASE}/data/images',
    'checkpoint_dir': f'{BASE}/checkpoints',
    'epochs':         30,
    'batch_size':     16,
    'image_size':     224,
    'lr':             1e-3,
    'weight_decay':   1e-4,
    'dropout':        0.4,
    'num_workers':    0,
    'val_split':      0.15,
}
print('Config ready.')

# ── Augmentation ──────────────────────────────────────────────────────────────

def resize_with_annotations(
    image:       np.ndarray,
    bboxes:      list[list[float]],
    masks:       list[np.ndarray],
    target_size: tuple[int, int],
) -> tuple[np.ndarray, list[list[float]], list[np.ndarray]]:
    h, w = image.shape[:2]
    W, H = target_size
    image  = cv2.resize(image, (W, H), interpolation=cv2.INTER_LINEAR)
    sx, sy = W / w, H / h
    new_bboxes = [[x * sx, y * sy, bw * sx, bh * sy] for x, y, bw, bh in bboxes]
    new_masks  = [
        cv2.resize(m.astype(np.uint8), (W, H),
                   interpolation=cv2.INTER_NEAREST).astype(bool)
        for m in masks
    ]
    return image, new_bboxes, new_masks


def normalize(image: np.ndarray) -> np.ndarray:
    image = image.astype(np.float32) / 255.0
    mean  = np.array([0.485, 0.456, 0.406], dtype=np.float32)
    std   = np.array([0.229, 0.224, 0.225], dtype=np.float32)
    return (image - mean) / std


def random_horizontal_flip(
    image:  np.ndarray,
    bboxes: list[list[float]],
    masks:  list[np.ndarray],
    p: float = 0.5,
) -> tuple[np.ndarray, list[list[float]], list[np.ndarray]]:
    if random.random() > p:
        return image, bboxes, masks
    h, w   = image.shape[:2]
    image  = cv2.flip(image, 1)
    new_bboxes = [[w - x - bw, y, bw, bh] for x, y, bw, bh in bboxes]
    new_masks  = [cv2.flip(m.astype(np.uint8), 1).astype(bool) for m in masks]
    return image, new_bboxes, new_masks


def random_affine(
    image:         np.ndarray,
    bboxes:        list[list[float]],
    masks:         list[np.ndarray],
    max_angle:     float = 15.0,
    max_translate: float = 0.1,
    scale_range:   tuple[float, float] = (0.9, 1.1),
) -> tuple[np.ndarray, list[list[float]], list[np.ndarray]]:
    """Random rotation + translation + scale. Bboxes re-derived from corner transforms."""
    h, w   = image.shape[:2]
    angle  = random.uniform(-max_angle, max_angle)
    tx     = random.uniform(-max_translate, max_translate) * w
    ty     = random.uniform(-max_translate, max_translate) * h
    scale  = random.uniform(*scale_range)
    cx, cy = w / 2.0, h / 2.0

    M = cv2.getRotationMatrix2D((cx, cy), angle, scale)
    M[0, 2] += tx
    M[1, 2] += ty

    image = cv2.warpAffine(image, M, (w, h), flags=cv2.INTER_LINEAR,
                           borderMode=cv2.BORDER_REFLECT_101)

    def transform_point(px, py):
        return (
            M[0, 0] * px + M[0, 1] * py + M[0, 2],
            M[1, 0] * px + M[1, 1] * py + M[1, 2],
        )

    new_bboxes: list[list[float]] = []
    for x, y, bw, bh in bboxes:
        corners = [
            transform_point(x,      y),
            transform_point(x + bw, y),
            transform_point(x,      y + bh),
            transform_point(x + bw, y + bh),
        ]
        xs = [c[0] for c in corners]; ys = [c[1] for c in corners]
        nx  = max(0.0,     min(xs));  ny  = max(0.0,     min(ys))
        nx2 = min(float(w), max(xs)); ny2 = min(float(h), max(ys))
        new_bboxes.append([nx, ny, nx2 - nx, ny2 - ny])

    new_masks = [
        cv2.warpAffine(m.astype(np.uint8), M, (w, h),
                       flags=cv2.INTER_NEAREST,
                       borderMode=cv2.BORDER_CONSTANT, borderValue=0).astype(bool)
        for m in masks
    ]
    return image, new_bboxes, new_masks


def color_jitter(image: np.ndarray) -> np.ndarray:
    """Random brightness, contrast, and HSV saturation jitter."""
    alpha = random.uniform(0.7, 1.3)
    beta  = random.uniform(-30, 30)
    image = cv2.convertScaleAbs(image, alpha=alpha, beta=beta)
    hsv   = cv2.cvtColor(image, cv2.COLOR_BGR2HSV).astype(np.float32)
    hsv[:, :, 1] = np.clip(hsv[:, :, 1] * random.uniform(0.7, 1.3), 0, 255)
    return cv2.cvtColor(hsv.astype(np.uint8), cv2.COLOR_HSV2BGR)


def random_crop(
    image:      np.ndarray,
    bboxes:     list[list[float]],
    masks:      list[np.ndarray],
    crop_ratio: float = 0.9,
) -> tuple[np.ndarray, list[list[float]], list[np.ndarray]]:
    """Crop retaining >= crop_ratio of each dimension. Drops boxes clipped below 5px."""
    h, w  = image.shape[:2]
    new_w = int(w * random.uniform(crop_ratio, 1.0))
    new_h = int(h * random.uniform(crop_ratio, 1.0))
    x0    = random.randint(0, w - new_w)
    y0    = random.randint(0, h - new_h)
    image = image[y0:y0 + new_h, x0:x0 + new_w]

    new_bboxes: list[list[float]] = []
    new_masks:  list[np.ndarray]  = []
    for (x, y, bw, bh), mask in zip(bboxes, masks):
        nx  = max(0.0,          x  - x0)
        ny  = max(0.0,          y  - y0)
        nx2 = min(float(new_w), x + bw - x0)
        ny2 = min(float(new_h), y + bh - y0)
        if nx2 - nx > 5 and ny2 - ny > 5:
            new_bboxes.append([nx, ny, nx2 - nx, ny2 - ny])
            new_masks.append(mask[y0:y0 + new_h, x0:x0 + new_w])

    return image, new_bboxes, new_masks


print('Augmentation helpers defined.')

# ── RLE Loader ────────────────────────────────────────────────────────────────

def rle_to_mask(rle_counts: list[int], height: int, width: int) -> np.ndarray:
    """Decode a flat RLE list back to a boolean 2D mask."""
    flat: list[int] = []
    val = 0
    for count in rle_counts:
        flat.extend([val] * count)
        val = 1 - val
    arr   = np.array(flat, dtype=np.uint8)
    total = height * width
    if arr.size < total:
        arr = np.pad(arr, (0, total - arr.size))
    return arr[:total].reshape(height, width).astype(bool)


# ── Dataset ───────────────────────────────────────────────────────────────────

class COCOObjectDataset(Dataset):
    """
    Loads COCO-format annotations and returns
        image   : FloatTensor [3, H, W]  (ImageNet-normalised)
        label   : LongTensor  []          (0-indexed primary category)
        bboxes  : FloatTensor [N, 4]      (x, y, w, h — pixel coords)
        masks   : BoolTensor  [N, H, W]
    """

    def __init__(
        self,
        coco_path:   str,
        image_root:  str,
        target_size: tuple[int, int] = (224, 224),
        augment:     bool = True,
        max_masks:   int  = 10,
    ):
        self.image_root  = Path(image_root)
        self.target_size = target_size    # (W, H)
        self.augment     = augment
        self.max_masks   = max_masks

        with open(coco_path) as f:
            coco = json.load(f)

        self.categories  = {c['id']: c['name'] for c in coco['categories']}
        self.num_classes = len(self.categories)
        sorted_ids       = sorted(self.categories.keys())
        self.id_to_idx   = {cid: i for i, cid in enumerate(sorted_ids)}

        ann_by_image: dict[int, list[dict]] = {}
        for ann in coco['annotations']:
            ann_by_image.setdefault(ann['image_id'], []).append(ann)

        self.samples: list[dict] = []
        for img in coco['images']:
            anns = ann_by_image.get(img['id'], [])
            if not anns:
                continue
            img_path = self.image_root / img['file_name']
            if not img_path.exists():
                candidates = list(self.image_root.rglob(img['file_name']))
                if not candidates:
                    continue
                img_path = candidates[0]
            self.samples.append({
                'path':   str(img_path),
                'height': img['height'],
                'width':  img['width'],
                'anns':   anns,
            })

        print(
            f'[Dataset] {len(self.samples)} images | '
            f'{self.num_classes} categories | augment={augment}'
        )

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> dict:
        sample = self.samples[idx]
        bgr    = cv2.imread(sample['path'])
        W_out, H_out = self.target_size

        # Graceful fallback for missing files
        if bgr is None:
            return {
                'image':  torch.zeros(3, H_out, W_out),
                'label':  torch.tensor(0, dtype=torch.long),
                'bboxes': torch.zeros(1, 4),
                'masks':  torch.zeros(1, H_out, W_out, dtype=torch.bool),
            }

        image  = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
        anns   = sample['anns'][:self.max_masks]
        bboxes = [a['bbox'] for a in anns]

        masks: list[np.ndarray] = []
        for a in anns:
            seg = a['segmentation']
            if isinstance(seg, dict) and 'counts' in seg:
                mask = rle_to_mask(seg['counts'], seg['size'][0], seg['size'][1])
            else:
                mask = np.zeros((sample['height'], sample['width']), dtype=bool)
            masks.append(mask)

        # Resize first
        image, bboxes, masks = resize_with_annotations(
            image, bboxes, masks, self.target_size
        )

        if self.augment:
            image = color_jitter(image)
            image, bboxes, masks = random_horizontal_flip(image, bboxes, masks)
            image, bboxes, masks = random_affine(image, bboxes, masks)
            image, bboxes, masks = random_crop(image, bboxes, masks)
            # Resize back to target after crop
            image, bboxes, masks = resize_with_annotations(
                image, bboxes, masks, self.target_size
            )

        image_norm   = normalize(image)
        image_tensor = torch.from_numpy(image_norm).permute(2, 0, 1).float()

        if bboxes:
            bbox_tensor = torch.tensor(bboxes, dtype=torch.float32)
            mask_tensor = torch.tensor(
                np.stack([m.astype(np.uint8) for m in masks], axis=0),
                dtype=torch.bool,
            )
        else:
            bbox_tensor = torch.zeros(1, 4,            dtype=torch.float32)
            mask_tensor = torch.zeros(1, H_out, W_out, dtype=torch.bool)

        primary_cat_id = anns[0]['category_id'] if anns else sorted(self.id_to_idx)[0]
        label = torch.tensor(self.id_to_idx[primary_cat_id], dtype=torch.long)

        return {
            'image':  image_tensor,
            'label':  label,
            'bboxes': bbox_tensor,
            'masks':  mask_tensor,
        }


print('COCOObjectDataset defined.')

# ── Collate Function & DataLoader Factory ─────────────────────────────────────

def collate_fn(batch: list[dict]) -> dict:
    """Collate variable-N-annotation samples into a batch."""
    return {
        'image':  torch.stack([b['image']  for b in batch]),
        'label':  torch.stack([b['label']  for b in batch]),
        'bboxes': [b['bboxes'] for b in batch],
        'masks':  [b['masks']  for b in batch],
    }


def get_dataloaders(
    coco_path:   str,
    image_root:  str,
    batch_size:  int   = 16,
    val_split:   float = 0.15,
    target_size: tuple[int, int] = (224, 224),
    num_workers: int   = 2,
) -> tuple[DataLoader, DataLoader, int]:

    # Returns (train_loader, val_loader, num_classes)
    base_ds = COCOObjectDataset(
        coco_path, image_root, target_size=target_size, augment=False
    )
    n_total = len(base_ds)
    n_val   = max(1, int(n_total * val_split))
    n_train = n_total - n_val

    gen = torch.Generator().manual_seed(42)
    train_indices, val_indices = torch.utils.data.random_split(
        range(n_total), [n_train, n_val], generator=gen
    )

    train_ds_full = COCOObjectDataset(
        coco_path, image_root, target_size=target_size, augment=True
    )
    val_ds_full = COCOObjectDataset(
        coco_path, image_root, target_size=target_size, augment=False
    )

    train_ds = torch.utils.data.Subset(train_ds_full, list(train_indices))
    val_ds   = torch.utils.data.Subset(val_ds_full,   list(val_indices))

    _pin = torch.cuda.is_available()
    train_loader = DataLoader(
        train_ds, batch_size=batch_size, shuffle=True,
        num_workers=num_workers, pin_memory=_pin, collate_fn=collate_fn,
    )
    val_loader = DataLoader(
        val_ds, batch_size=batch_size, shuffle=False,
        num_workers=num_workers, pin_memory=_pin, collate_fn=collate_fn,
    )
    return train_loader, val_loader, base_ds.num_classes


print('DataLoader factory defined.')

# ── Model Architecture — CCNN (AugleNet) ──────────────────────────────────────

class ConvBnRelu(nn.Module):
    """Conv2d then BatchNorm2d then ReLU building block."""
    def __init__(self, in_ch: int, out_ch: int, kernel: int = 3, stride: int = 1):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel, stride=stride,
                      padding=kernel // 2, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        return self.block(x)


class ResidualBlock(nn.Module):
    """
    Two-layer residual block.
    skip_proj=True  -> 1x1 conv to match channels (when in_ch != out_ch)
    skip_proj=False -> identity shortcut (requires in_ch == out_ch)
    pool=True       -> MaxPool2d(2,2) after residual add
    """
    def __init__(self, in_ch: int, out_ch: int,
                 skip_proj: bool = False, pool: bool = False):
        super().__init__()
        self.conv1    = ConvBnRelu(in_ch, out_ch, kernel=3)
        self.conv2    = nn.Sequential(
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
        )
        self.shortcut = nn.Conv2d(in_ch, out_ch, 1, bias=False) if skip_proj else nn.Identity()
        self.relu     = nn.ReLU(inplace=True)
        self.pool     = nn.MaxPool2d(2, 2) if pool else nn.Identity()

    def forward(self, x):
        residual = self.shortcut(x)
        out      = self.conv1(x)
        out      = self.conv2(out)
        out      = self.relu(out + residual)
        return self.pool(out)


class CCNN(nn.Module):
    """
    Custom 4-stage CNN backbone.
    Input:  (B, 3, H, W)  -- H, W >= 32
    Output: (B, num_classes)  -- log-softmax
    """
    def __init__(self, num_classes: int, dropout: float = 0.4):
        super().__init__()
        self.stem   = ConvBnRelu(3, 32, kernel=3)
        self.stage1 = ResidualBlock(32,  64,  skip_proj=True,  pool=False)
        self.stage2 = ResidualBlock(64,  128, skip_proj=True,  pool=True)
        self.stage3 = ResidualBlock(128, 256, skip_proj=True,  pool=True)
        self.stage4 = ResidualBlock(256, 256, skip_proj=False, pool=True)
        self.gap     = nn.AdaptiveAvgPool2d(1)
        self.dropout = nn.Dropout(dropout)
        self.fc      = nn.Linear(256, num_classes)
        self.log_sm  = nn.LogSoftmax(dim=1)
        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.ones_(m.weight); nn.init.zeros_(m.bias)
            elif isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight); nn.init.zeros_(m.bias)

    def forward(self, x):
        x = self.stem(x)
        x = self.stage1(x)
        x = self.stage2(x)
        x = self.stage3(x)
        x = self.stage4(x)
        x = self.gap(x).flatten(1)
        x = self.dropout(x)
        x = self.fc(x)
        return self.log_sm(x)

    def count_parameters(self):
        return sum(p.numel() for p in self.parameters() if p.requires_grad)


print('Custom CNN defined.')

# ── Metrics & Utilities ───────────────────────────────────────────────────────

def compute_accuracy(logits, labels):
    return (logits.argmax(dim=1) == labels).float().mean().item()


def compute_top_k_accuracy(logits, labels, k=3):
    topk  = logits.topk(min(k, logits.size(1)), dim=1).indices
    match = topk.eq(labels.unsqueeze(1).expand_as(topk))
    return match.any(dim=1).float().mean().item()


def make_grid_of_augmented(images, n=8):
    """Denormalise a batch of images to TensorBoard grid."""
    mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
    std  = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)
    imgs = (images[:n].cpu() * std + mean).clamp(0, 1)
    return torchvision.utils.make_grid(imgs, nrow=4)


def save_checkpoint(state, path):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    torch.save(state, path)


print('Metrics and utilities defined.')

# ── Train / Eval Loops ────────────────────────────────────────────────────────

def train_one_epoch(model, loader, criterion, optimizer, device, writer, epoch, global_step):
    model.train()
    total_loss, total_acc, n = 0.0, 0.0, 0

    for batch in loader:
        images = batch['image'].to(device)
        labels = batch['label'].to(device)

        optimizer.zero_grad()
        logits = model(images)
        loss   = criterion(logits, labels)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
        optimizer.step()

        bs = images.size(0)
        total_loss += loss.item() * bs
        total_acc  += compute_accuracy(logits.detach(), labels) * bs
        n          += bs

        writer.add_scalar('train/step_loss', loss.item(), global_step[0])
        global_step[0] += 1

    return {'loss': total_loss / n, 'acc': total_acc / n}


@torch.no_grad()
def evaluate(model, loader, criterion, device):
    model.eval()
    total_loss, total_acc, total_top3, n = 0.0, 0.0, 0.0, 0

    for batch in loader:
        images = batch['image'].to(device)
        labels = batch['label'].to(device)
        logits = model(images)
        loss   = criterion(logits, labels)

        bs = images.size(0)
        total_loss += loss.item() * bs
        total_acc  += compute_accuracy(logits, labels) * bs
        total_top3 += compute_top_k_accuracy(logits, labels, k=3) * bs
        n          += bs

    return {'loss': total_loss / n, 'acc': total_acc / n, 'top3': total_top3 / n}


print('Train/eval loops defined.')

# ── Setup — Data, Model, Optimizer ───────────────────────────────────────────

train_loader, val_loader, num_classes = get_dataloaders(
    coco_path=CFG['coco_path'],
    image_root=CFG['image_root'],
    batch_size=CFG['batch_size'],
    val_split=CFG['val_split'],
    target_size=(CFG['image_size'], CFG['image_size']),
    num_workers=CFG['num_workers'],
)
print(f'Classes: {num_classes} | Train: {len(train_loader)} batches | Val: {len(val_loader)} batches')

model     = CCNN(num_classes=num_classes, dropout=CFG['dropout']).to(DEVICE)
print(f'CCNN parameters: {model.count_parameters():,}')

criterion = nn.NLLLoss()
optimizer = optim.AdamW(model.parameters(), lr=CFG['lr'], weight_decay=CFG['weight_decay'])
scheduler = CosineAnnealingLR(optimizer, T_max=CFG['epochs'], eta_min=1e-6)

run_name = f"ccnn_{time.strftime('%Y%m%d_%H%M%S')}"
log_dir  = f'{BASE}/runs/{run_name}'
Path(log_dir).mkdir(parents=True, exist_ok=True)
writer   = SummaryWriter(log_dir=log_dir)

print(f'TensorBoard run: {log_dir}')

# ── Training Loop ─────────────────────────────────────────────────────────────

# To monitor live in TensorBoard:
# %load_ext tensorboard
# %tensorboard --logdir runs

best_val_acc = 0.0
global_step  = [0]
history      = []

for epoch in range(1, CFG['epochs'] + 1):
    t0 = time.time()

    train_m = train_one_epoch(
        model, train_loader, criterion, optimizer,
        DEVICE, writer, epoch, global_step
    )
    val_m   = evaluate(model, val_loader, criterion, DEVICE)
    scheduler.step()
    elapsed = time.time() - t0

    writer.add_scalars('loss', {'train': train_m['loss'], 'val': val_m['loss']}, epoch)
    writer.add_scalars('acc',  {'train': train_m['acc'],  'val': val_m['acc']},  epoch)
    writer.add_scalar('val/top3_acc', val_m['top3'], epoch)
    writer.add_scalar('lr', optimizer.param_groups[0]['lr'], epoch)

    if epoch == 1 or epoch % 5 == 0:
        try:
            sample_batch = next(iter(train_loader))
            grid = make_grid_of_augmented(sample_batch['image'])
            writer.add_image('augmented_samples', grid, epoch)
        except Exception as e:
            print(f'[WARN] Image grid logging skipped: {e}')

    print(
        f'Epoch {epoch:3d}/{CFG["epochs"]} | '
        f'Train loss {train_m["loss"]:.4f} acc {train_m["acc"]:.3f} | '
        f'Val loss {val_m["loss"]:.4f} acc {val_m["acc"]:.3f} '
        f'top3 {val_m["top3"]:.3f} | '
        f'LR {optimizer.param_groups[0]["lr"]:.2e} | {elapsed:.1f}s'
    )

    if val_m['acc'] > best_val_acc:
        best_val_acc = val_m['acc']
        ckpt_dir = Path(CFG['checkpoint_dir']) / run_name
        ckpt_dir.mkdir(parents=True, exist_ok=True)
        torch.save({
            'epoch':           epoch,
            'model_state':     model.state_dict(),
            'optimizer_state': optimizer.state_dict(),
            'val_acc':         best_val_acc,
            'num_classes':     num_classes,
        }, ckpt_dir / 'best.pt')
        print(f'   New best val acc: {best_val_acc:.4f} — checkpoint saved to Drive')

    history.append({
        'epoch': epoch,
        **{f'train_{k}': v for k, v in train_m.items()},
        **{f'val_{k}':   v for k, v in val_m.items()},
    })

# Save final model + history to Drive
ckpt_dir = Path(CFG['checkpoint_dir']) / run_name
ckpt_dir.mkdir(parents=True, exist_ok=True)
torch.save(
    {'epoch': CFG['epochs'], 'model_state': model.state_dict(), 'num_classes': num_classes},
    ckpt_dir / 'final.pt'
)
with open(ckpt_dir / 'history.json', 'w') as f:
    json.dump(history, f, indent=2)

writer.close()
print(f'\nTraining complete. Best val acc: {best_val_acc:.4f}')
print(f'Checkpoints saved -> {ckpt_dir}')

# ── Training Curves ───────────────────────────────────────────────────────────

if not history:
    print('No history to plot — run the training loop first.')
else:
    epochs_list = [h['epoch']      for h in history]
    t_loss      = [h['train_loss'] for h in history]
    v_loss      = [h['val_loss']   for h in history]
    t_acc       = [h['train_acc']  for h in history]
    v_acc       = [h['val_acc']    for h in history]

    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    axes[0].plot(epochs_list, t_loss, label='Train')
    axes[0].plot(epochs_list, v_loss, label='Val')
    axes[0].set_title('Loss'); axes[0].set_xlabel('Epoch')
    axes[0].legend(); axes[0].grid(True)

    axes[1].plot(epochs_list, t_acc, label='Train')
    axes[1].plot(epochs_list, v_acc, label='Val')
    axes[1].set_title('Accuracy'); axes[1].set_xlabel('Epoch')
    axes[1].legend(); axes[1].grid(True)

    plt.tight_layout()
    curve_path = f'{BASE}/training_curves.png'
    plt.savefig(curve_path, dpi=150)
    plt.show()
    print(f'Best val acc: {best_val_acc:.4f}')
    print(f'Curve saved -> {curve_path}')
